version: '3.7'

services:
  app:
    # uwsgi + flask env
    build: ./infra/app
    tty: true
    ports:
      - 3031:3031
    volumes:
      - ./infra/app:/usr/src/app/
      # - ./log:/var/log/uwsgi
    # logging:
    #   driver: "json-file" # defaults if not specified
  web:
    # nginx server
    image: nginx:1.18-alpine
    ports:
      - 8080:8080
    links:
      - app
    volumes:
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf      
